Notebooks Update
joewood/react-iceberg pull request #6
Opened 2021-08-18 05:34 UTC by Yves-Noel

Python file added in the test section.

2021-08-18 20:39 UTC, joewood requested changes
Looks good other than the API. Remember to set the environment variable in your shell once it's setup. You shouldn't even check-in API Keys. 

Also can you remove the whitespace lines in this file?

2021-08-18 20:39 UTC, joewood commented on test/app/Intro Notebook.py
> +quandl.ApiConfig.api_key = '38VWdHpGVLZs94hZCMC1'
Can you remove the API key from the code. Instead you should use an environment variable using:

```python
import os
quandl.ApiConfig.api_key =  os.environ["QUANDL_API_KEY"]
```

2021-08-18 22:10 UTC, Yves-Noel reviewed
Made a minor update on line 7 and 8
Cleaned code by deleting whitespace

2021-08-19 12:05 UTC, joewood reviewed
Great thanks, merging this file.

2021-08-19 12:05 UTC, merged